// Originalmente gerado por tool/gen_elements.py; MANTIDO À MÃO desde 2026-08-26.

import 'package:verovio_dart/src/core/vrvdef.dart';
import 'package:verovio_dart/src/model/control_elements_gen.dart';
import 'package:verovio_dart/src/model/layer_elements_gen.dart';
import 'package:verovio_dart/src/model/misc_elements_gen.dart';
import 'package:verovio_dart/src/model/object.dart';

/// Registers the element classes living in the `*_gen.dart` files, with the
/// same MEI element names as the C++ `ClassRegistrar` static instances
/// (`grep -rn "ClassRegistrar" origin/src/src/*.cpp`).
///
/// Originally generated by `tool/gen_elements.py`; hand-maintained since
/// 2026-08-26 (the generator was retired — see `prompts/reports/04i.md`).
void registerGeneratedClasses(ObjectFactory f) {
  f.register('accid', ClassId.accid, Accid.new);
  f.register('anchoredText', ClassId.anchoredText, AnchoredText.new);
  f.register('annotScore', ClassId.annotScore, AnnotScore.new);
  f.register('arpeg', ClassId.arpeg, Arpeg.new);
  f.register('artic', ClassId.artic, Artic.new);
  f.register('beam', ClassId.beam, Beam.new);
  f.register('beamSpan', ClassId.beamSpan, BeamSpan.new);
  f.register('beatRpt', ClassId.beatRpt, BeatRpt.new);
  f.register('bracketSpan', ClassId.bracketSpan, BracketSpan.new);
  f.register('breath', ClassId.breath, Breath.new);
  // 'btrem', not 'bTrem' (mirrors `btrem.cpp:32`).
  f.register('btrem', ClassId.bTrem, BTrem.new);
  f.register('caesura', ClassId.caesura, Caesura.new);
  f.register('chord', ClassId.chord, Chord.new);
  f.register('course', ClassId.course, Course.new);
  f.register('cpMark', ClassId.cpMark, CpMark.new);
  f.register('custos', ClassId.custos, Custos.new);
  f.register('dir', ClassId.dir, Dir.new);
  f.register('div', ClassId.div, Div.new);
  f.register('dot', ClassId.dot, Dot.new);
  f.register('dynam', ClassId.dynam, Dynam.new);
  f.register('ending', ClassId.ending, Ending.new);
  f.register('expansion', ClassId.expansion, Expansion.new);
  // 'f' mirrors `f.cpp:27` (`ClassRegistrar<F> s_factory("f", FIGURE)`).
  // Registered with `ClassId.f`, the value the Dart `F` object carries (see
  // report 04i for the C++ FIGURE ↔ Dart `f` note).
  f.register('f', ClassId.f, F.new);
  f.register('facsimile', ClassId.facsimile, Facsimile.new);
  f.register('fb', ClassId.fb, Fb.new);
  f.register('fermata', ClassId.fermata, Fermata.new);
  f.register('fig', ClassId.fig, Fig.new);
  f.register('fing', ClassId.fing, Fing.new);
  f.register('fTrem', ClassId.fTrem, FTrem.new);
  f.register('gliss', ClassId.gliss, Gliss.new);
  f.register('graceGrp', ClassId.graceGrp, GraceGrp.new);
  f.register('graphic', ClassId.graphic, Graphic.new);
  f.register('grpSym', ClassId.grpSym, GrpSym.new);
  f.register('hairpin', ClassId.hairpin, Hairpin.new);
  f.register('halfmRpt', ClassId.halfmRpt, HalfmRpt.new);
  f.register('harm', ClassId.harm, Harm.new);
  f.register(
      'alignmentreference', ClassId.alignmentReference, AlignmentReference.new);
  f.register('instrDef', ClassId.instrDef, InstrDef.new);
  f.register('keyAccid', ClassId.keyAccid, KeyAccid.new);
  f.register('keySig', ClassId.keysig, KeySig.new);
  f.register('label', ClassId.label, Label.new);
  f.register('labelAbbr', ClassId.labelAbbr, LabelAbbr.new);
  f.register('lb', ClassId.lb, Lb.new);
  f.register('ligature', ClassId.ligature, Ligature.new);
  f.register('lv', ClassId.lv, Lv.new);
  f.register('meterSig', ClassId.meterSig, MeterSig.new);
  f.register('meterSigGrp', ClassId.meterSigGrp, MeterSigGrp.new);
  f.register('mNum', ClassId.mnum, MNum.new);
  f.register('mordent', ClassId.mordent, Mordent.new);
  f.register('mRest', ClassId.mRest, MRest.new);
  f.register('mRpt', ClassId.mRpt, MRpt.new);
  f.register('mRpt2', ClassId.mRpt2, MRpt2.new);
  f.register('mSpace', ClassId.mSpace, MSpace.new);
  f.register('multiRest', ClassId.multiRest, MultiRest.new);
  f.register('multiRpt', ClassId.multiRpt, MultiRpt.new);
  f.register('nc', ClassId.nc, Nc.new);
  f.register('neume', ClassId.neume, Neume.new);
  f.register('num', ClassId.num, Num.new);
  f.register('octave', ClassId.octave, Octave.new);
  f.register('ornam', ClassId.ornam, Ornam.new);
  f.register('pb', ClassId.pb, Pb.new);
  f.register('pedal', ClassId.pedal, Pedal.new);
  f.register('pgFoot', ClassId.pgFoot, PgFoot.new);
  f.register('pgHead', ClassId.pgHead, PgHead.new);
  f.register('phrase', ClassId.phrase, Phrase.new);
  f.register('pitchInflection', ClassId.pitchInflection, PitchInflection.new);
  f.register('plica', ClassId.plica, Plica.new);
  f.register('proport', ClassId.proport, Proport.new);
  f.register('reh', ClassId.reh, Reh.new);
  f.register('rend', ClassId.rend, Rend.new);
  f.register('repeatMark', ClassId.repeatMark, RepeatMark.new);
  f.register('sb', ClassId.sb, Sb.new);
  f.register('slur', ClassId.slur, Slur.new);
  f.register('space', ClassId.space, Space.new);
  f.register('stem', ClassId.stem, Stem.new);
  f.register('surface', ClassId.surface, Surface.new);
  f.register('svg', ClassId.svg, Svg.new);
  f.register('syl', ClassId.syl, Syl.new);
  f.register('syllable', ClassId.syllable, Syllable.new);
  f.register('symbol', ClassId.symbol, Symbol.new);
  f.register('symbolDef', ClassId.symbolDef, SymbolDef.new);
  f.register('symbolTable', ClassId.symbolTable, SymbolTable.new);
  f.register('tabDurSym', ClassId.tabDurSym, TabDurSym.new);
  f.register('tabGrp', ClassId.tabGrp, TabGrp.new);
  f.register('tempo', ClassId.tempo, Tempo.new);
  f.register('tie', ClassId.tie, Tie.new);
  f.register('trill', ClassId.trill, Trill.new);
  f.register('tuning', ClassId.tuning, Tuning.new);
  f.register('tuplet', ClassId.tuplet, Tuplet.new);
  f.register('turn', ClassId.turn, Turn.new);
  f.register('verse', ClassId.verse, Verse.new);
}
